version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./GeoLite2-Country.mmdb:/app/GeoLite2-Country.mmdb
      - /etc/filter:/etc/filter
      - /var/log:/var/log
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"  # Пробрасываем порт 8080
    command: ["./filter"]
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
