FROM python:3.9-slim

WORKDIR /home/debian/proekt1/network-filter
COPY app.py .
COPY templates/ templates/
COPY static/ static/

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip && pip install flask psutil

CMD ["python", "app.py"]
