version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - /etc/filter:/etc/filter
      - /var/log:/var/log
    network_mode: "host"  # Используем сеть хоста
    privileged: true      # Максимальные привилегии
    command: ["./filter"]
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
