version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    volumes:
      - ./filter.db:/app/filter.db
    depends_on:
      - filter
    networks:
      - app-network

  filter:
    build:
      context: .
      dockerfile: Dockerfile.traffic
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./filter.db:/app/filter.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
